name: Manual Trigger
on: 
  push:
  workflow_dispatch: # manual trigger, troggered by user manually
jobs:
  MyJob:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Manual Trigger
        run: echo "manually triggerd"
