name: Slack Notification
on: workflow_dispatch
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{secrets.SLACK_WEBHOOK_URL}}
          webhook-type: incoming-webhook
          payload: |
            channel: "github-demo"
            text: "Welcome to Github Actions"
