name: variables demo
on: workflow_dispatch
env:
  TRAINER: "Murali Krishna"  # Workflow Level Variable
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLASS: "devops-2518"  # Job level variable
    steps:
      - name: Calling Workflow Level Variable
        run: echo "The trainer name is $TRAINER"
      - name: calling step level variable
        run: echo "today topic details are $TOPIC"
        env:
          TOPIC: "Github Actions"    # step level variable
      - name: Calling Job level variable
        run: echo "the class name is $CLASS"
      - name: call all vars
        run: echo "the trainer is $TRAINER, Class is $CLASS and topic $TOPIC"
      - name: calling repo variable
        run: echo "the username is ${{vars.MY_USERNAME}}"
  deploy:
    runs-on: ubuntu-latest
    env:
      CLASS: "devops2518"
    steps:
      - name: Calling Workflow Level Variable
        run: echo "The trainer is $TRAINER"
      - name: Calling Job level variable
        run: echo "the class is $CLASS"
      - name: calling default vars
        run: echo "the workflow run number is $GITHUB_RUN_NUMBER"
